<template>
  <div class="dashboard-container">
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
    <div>测试</div>
  </div>
</template>
<script setup lang="ts"></script>
